"""Formula registry — metadata for every formula_id in the graph."""

from __future__ import annotations

from typing import Any

FORMULA_REGISTRY: dict[str, dict[str, Any]] = {
    "PROFILE_V1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.profile_node",
        "function": "ProfileNode.execute",
        "inputs": ["DogProfileInput"],
        "outputs": ["profile"],
        "tables": [],
        "parameters": [],
        "consumers": ["breed", "biology", "risk"],
    },
    "BREED_RESOLVE_V1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.breed_node",
        "function": "BreedNode.execute",
        "inputs": ["profile"],
        "outputs": ["breed_names", "breed_rows"],
        "tables": ["breeds", "breed_aliases"],
        "parameters": [],
        "consumers": ["biology", "risk"],
    },
    "BIOLOGY_V2_1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.biology_node",
        "function": "BiologyNode.execute",
        "inputs": ["profile", "breed"],
        "outputs": ["biology"],
        "tables": ["breeds", "trait_purposes", "environmental_matrices"],
        "parameters": [],
        "consumers": ["risk", "epidemiology", "assessment"],
    },
    "RISK_V2_1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.risk_node",
        "function": "RiskNode.execute",
        "wrapped": "app.agent.stages.health_risk.compute_risks",
        "inputs": ["profile", "biology", "breed"],
        "outputs": ["risks", "meta", "healthInsights_source"],
        "tables": [
            "breed_conditions",
            "size_conditions",
            "bodytype_conditions",
            "coattype_conditions",
            "energy_conditions",
            "skulltype_conditions",
            "climate_conditions",
            "lifespan_conditions",
            "functiongroup_conditions",
            "weaknessgroup_conditions",
            "trait_interactions",
            "trait_benefits",
            "mixed_breed_matrix",
        ],
        "parameters": ["risk_interaction.INTERACTION_MIN", "risk_interaction.INTERACTION_MAX", "category_weights.*"],
        "consumers": ["epidemiology", "nutrition", "ingredient", "packages", "assessment", "validation"],
    },
    "EPIDEMIOLOGY_V2_1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.epidemiology_node",
        "function": "EpidemiologyNode.execute",
        "wrapped": "app.agent.stages.epidemiology.run_epidemiology_stage",
        "inputs": ["profile", "biology", "risk"],
        "outputs": ["epidemiology", "priority_conditions"],
        "tables": ["breed_conditions", "trait_condition tables"],
        "parameters": [],
        "consumers": ["activity", "nutrition"],
    },
    "ACTIVITY_V2_1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.activity_node",
        "function": "ActivityNode.execute",
        "inputs": ["epidemiology"],
        "outputs": ["management", "lifestyle_requirements"],
        "tables": ["condition_activities"],
        "parameters": [],
        "consumers": ["assessment", "export"],
    },
    "GROOMING_V1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.grooming_node",
        "function": "GroomingNode.execute",
        "inputs": ["profile", "biology"],
        "outputs": ["grooming_defs"],
        "tables": ["grooming_observation_defs"],
        "parameters": [],
        "consumers": ["assessment", "report"],
    },
    "NUTRITION_V2_1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.nutrition_node",
        "function": "NutritionNode.execute",
        "wrapped": "app.agent.stages.nutrition.run_nutrition_stage",
        "inputs": ["profile", "epidemiology"],
        "outputs": ["nutrient_targets"],
        "tables": ["condition_ingredients"],
        "parameters": [],
        "consumers": ["ingredient", "product", "export"],
    },
    "NUTRIENT_TARGET_V2_1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.ingredient_node",
        "function": "IngredientNode.execute",
        "wrapped": "app.agent.ingredient_engine.map_ingredients",
        "inputs": ["risk", "profile"],
        "outputs": ["ingredients"],
        "tables": ["condition_ingredients", "ingredient_evidence", "ingredient_mechanisms"],
        "parameters": [],
        "consumers": ["product", "package", "export", "evidence"],
    },
    "PRODUCT_MATCH_V2_1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.product_node",
        "function": "ProductNode.execute",
        "wrapped": "app.agent.stages.optimization.run_optimization_stage",
        "inputs": ["profile", "nutrition"],
        "outputs": ["products", "feeding_plan", "reports"],
        "tables": ["products", "product_components", "product_pricing", "product_feeding_rules"],
        "parameters": [],
        "consumers": ["package", "report", "export"],
    },
    "PACKAGE_OPTIMIZER_V2_1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.package_node",
        "function": "PackageNode.execute",
        "note": "Packages finalized in export via assemble_frontend_response (parity).",
        "inputs": ["product", "ingredient", "risk"],
        "outputs": ["package_ready"],
        "tables": ["package_tiers"],
        "parameters": ["score_weights.*"],
        "consumers": ["export", "assessment"],
    },
    "ASSESSMENT_PROJECT_V1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.assessment_node",
        "function": "AssessmentNode.execute",
        "inputs": ["biology", "risk", "nutrition", "activity", "product"],
        "outputs": ["assessment_summary"],
        "tables": [],
        "parameters": [],
        "consumers": ["export", "validation"],
    },
    "REPORT_V1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.report_node",
        "function": "ReportNode.execute",
        "inputs": ["product", "assessment"],
        "outputs": ["reports"],
        "tables": [],
        "parameters": [],
        "consumers": ["export"],
    },
    "CONFIDENCE_V1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.confidence_node",
        "function": "ConfidenceNode.execute",
        "inputs": ["risk"],
        "outputs": ["confidence_summary"],
        "tables": [],
        "parameters": [],
        "consumers": ["validation", "trace"],
    },
    "EVIDENCE_V1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.evidence_node",
        "function": "EvidenceNode.execute",
        "inputs": ["risk", "ingredient"],
        "outputs": ["evidence_bundle"],
        "tables": ["ingredient_evidence", "clinical_evidence_base"],
        "parameters": [],
        "consumers": ["validation", "trace"],
    },
    "VALIDATION_V1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.validation_node",
        "function": "ValidationNode.execute",
        "inputs": ["assessment", "risk", "nutrition", "product"],
        "outputs": ["validation"],
        "tables": [],
        "parameters": [],
        "consumers": ["export", "trace"],
    },
    "TRACE_V1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.trace_node",
        "function": "TraceNode.execute",
        "inputs": [],
        "outputs": ["trace_bundle"],
        "tables": [],
        "parameters": [],
        "consumers": ["export"],
    },
    "EXPORT_LEGACY_V1": {
        "version": "2.1.0",
        "module": "app.agent.nodes.export_node",
        "function": "ExportNode.execute",
        "wrapped": "app.agent.response_assembler.assemble_frontend_response",
        "inputs": ["biology", "epidemiology", "nutrition", "activity", "product", "risk", "report"],
        "outputs": ["legacy_json"],
        "tables": [],
        "parameters": [],
        "consumers": ["api", "frontend", "validation_console"],
    },
}


def get_formula(formula_id: str) -> dict[str, Any]:
    if formula_id not in FORMULA_REGISTRY:
        raise KeyError(f"Unknown formula_id: {formula_id}")
    return dict(FORMULA_REGISTRY[formula_id])


def list_formulas() -> list[str]:
    return sorted(FORMULA_REGISTRY.keys())
